In [ ]:
import numpy as np

In [1]:
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [82]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [83]:
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [84]:
b = a.reshape(3, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [85]:
c = a.reshape(6, 2)
c

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [86]:
d = a.reshape(4, 3)
d

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [87]:
e = a.reshape(2, 6)
e

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [88]:
f = a.reshape(12, 1)
f

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [89]:
# Создать 5 двумерных массивов разной формы из массива a. 
# Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [90]:
b1 = a.reshape(-1, 4)
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [91]:
c1 = np.reshape(a, (-1, 6))
c1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [92]:
d1 = np.reshape(a, (-1, 3))
d1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [93]:
e1 = a.reshape(2, -1)
e1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [94]:
f1 = np.reshape(a, (12, -1))
f1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [95]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

# Ответ: нет

In [96]:
print(f'Размерность f1: {f1.ndim}')
print(f'Форма f1: {f1.shape}')

Размерность f1: 2
Форма f1: (12, 1)


In [97]:
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
# со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [98]:
a1 = np.random.randn(3, 4)
a1

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [99]:
a1.size

12

In [100]:
b2 = a1.ravel()
b2

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975])

In [101]:
b2.shape

(12,)

In [102]:
a1.size == b2.size

True

In [103]:
c2 = a1.flatten()
c2

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975])

In [104]:
a1.size == c2.size

True

In [105]:
# Создать массив a2, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [106]:
a2 = np.arange(20, 0, -2)
a2

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [107]:
# Создать массив b3, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
# В чем разница между массивами a2 и b3? 

# Ответ: разница есть, так как массив a2 - одномерный, b3 - двумерный

In [108]:
b3 = np.arange(20, 1, -2).reshape(1, 10)
b3

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [109]:
print(f'Размерность a2: {a2.ndim}')
print(f'Форма a2: {a2.shape}')

Размерность a2: 1
Форма a2: (10,)


In [110]:
print(f'Размерность b3: {b3.ndim}')
print(f'Форма b3: {b3.shape}')

Размерность b3: 2
Форма b3: (1, 10)


In [111]:
np.array_equal(a2, b3)

False

In [112]:
# Вертикально соединить массивы a4 и b4. 
# a4 - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
# чем число строк двумерного массива b4, состоящего из единиц. 
# Итоговый массив v должен иметь атрибут size, равный 10.

In [114]:
a4 = np.zeros((2, 2))
b4 = np.ones((3, 2))
v = np.vstack((a4, b4))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [115]:
v.size

10

In [116]:
v = np.concatenate((a4, b4), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [117]:
v.size

10

In [118]:
# Создать одномерный массив а5, состоящий из последовательности целых чисел от 0 до 12. 
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
# Получить матрицу At путем транспонирования матрицы A. 
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

# Ответ: размер матрицы B = 4 на 4. Обратную матрицу для матрицы В вычислить не удасться, так как определитель матрицы В = 0

In [119]:
a5 = np.arange(0, 12)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [120]:
A = a5.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [121]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [122]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [123]:
print(f'Размерность B: {B.ndim}')
print(f'Форма B: {B.shape}')
B.size

Размерность B: 2
Форма B: (4, 4)


16

In [124]:
np.linalg.det(B)

0.0

In [125]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [126]:
np.random.seed(42)

In [127]:
# Создайте одномерный массив c4, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел 
# от 0 до 16 невключительно.

In [128]:
c4 = np.arange(0, 16)
c4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [129]:
# Поменяйте его форму так, чтобы получилась квадратная матрица C. 
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
# Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [131]:
C = c4.reshape(4, 4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [132]:
D = B + (C * 10)
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [133]:
D_opr = np.linalg.det(D)
D_opr

5.18953807259442e-26

In [134]:
D_rang = np.linalg.matrix_rank(D)
D_rang

2

In [135]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

In [ ]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
# Убедитесь, что в матрице D_inv остались только нули и единицы. 
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, 
# получите матрицу E размером 4x4.  
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
# должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
# для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [136]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0
D_inv[mask_positive] = 1
D_inv[mask_negative] = 0
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [138]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [139]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [137]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10,  11],
       [ 32,  13, 212, 302]])

In [140]:
print(f'Размерность E: {E.ndim}')
print(f'Форма E: {E.shape}')

Размерность E: 2
Форма E: (4, 4)
